plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

port: 4002

styles:

remote_theme: kosatyi/sjt

exclude:
  - node_modules
  - vendor
  - src

javascript:

baseurl: /browserhash
navigation: false
projects: true

brand: browserhash
title: Browserhash.js
description: Advanced fingerprint javascript library

author:
  name: Stepan Kosatyi
  url: http://www.kosatyi.com/
