gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

port: 4002
remote_theme: kosatyi/sjt

exclude:
  - node_modules
  - vendor
  - src

baseurl: /browserhash
navigation: false
projects: true

brand: browserhash
title: Browserhash.js
description: Advanced fingerprint javascript library
logo: fondy.svg

styles:
javascript:


author:
  name: Stepan Kosatyi
  url: http://www.kosatyi.com/
