plugins:
  - jekyll-seo-tag

port: 4002

styles:

remote_theme: kosatyi/sjt

exclude:
  - node_modules
  - vendor
  - src

javascript:

baseurl: /browserhash

navigation: false

projects: true

brand: browserhash
title: Browserhash.js
description: Advanced fingerprint javascript library
analytics: UA-37629144-1

author:
  name: Stepan Kosatyi
  url: http://www.kosatyi.com/

toolbar:
